[font]
size = 13.25
normal = { family = "0xProto Nerd Font", style = "Regular" }

[shell]
program = "/bin/zsh"
args = [
	"-c",
	"source ~/.zshrc && exec /opt/homebrew/bin/tmux new-session -A -s main"
]

[window]
opacity = 0.75
blur = true
startup_mode = "Fullscreen"
option_as_alt = "OnlyRight"
dynamic_padding = true
